# Generated by Django 3.2.12 on 2022-08-15 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='end',
        ),
    ]
