# Generated by Django 3.2.12 on 2022-08-15 22:58

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_question_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='deadline',
            field=models.DateTimeField(default=polls.models.date_limit),
        ),
    ]
