# Generated by Django 3.2.12 on 2022-08-22 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_userprofileinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='userVoting',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.userprofileinfo'),
        ),
    ]
