# Generated by Django 3.2.12 on 2022-08-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_choice_uservoting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='userVoting',
        ),
    ]
