# Generated by Django 3.2.12 on 2022-08-22 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='username',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.userprofileinfo'),
        ),
    ]
