# Generated by Django 3.2.12 on 2022-08-22 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_question_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='username',
        ),
    ]
