# Generated by Django 3.2.12 on 2022-08-22 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_remove_question_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='voter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.userprofileinfo'),
        ),
    ]
