# Generated by Django 3.2.12 on 2022-08-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_choice_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='voter',
        ),
    ]
