# Generated by Django 3.2.12 on 2022-08-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_choice_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='Voter_username',
            field=models.CharField(default='anonimus user', max_length=30),
        ),
    ]
