# Generated by Django 3.2.12 on 2022-08-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_choice_voter_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='Voter_username',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='Voter',
        ),
        migrations.AddField(
            model_name='vote',
            name='Voter_username',
            field=models.CharField(default='anonimus user', max_length=30),
        ),
    ]
