# Generated by Django 3.2.12 on 2022-08-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_vote_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='num_votes',
            field=models.IntegerField(default=0),
        ),
    ]
