# Generated by Django 3.2.12 on 2022-08-23 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_vote_num_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='Voter_username',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.userprofileinfo'),
        ),
    ]
