# Generated by Django 3.2.12 on 2022-08-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_alter_vote_voter_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='Voter_username',
            field=models.CharField(default='anonimus user', max_length=30),
        ),
    ]
